sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t 040772/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true 040772/react-test npm test
