sudo: required
dist: focal

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_3fcb6d2b8e4a_key -iv $encrypted_3fcb6d2b8e4a_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash >  /dev/null;
  - source $HOME//google-cloud-sdk/path.bash.inc 
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file activate-service.json
  - docker build -t 040772/react-test -f ./client/Dockerfile.dev ./client
