apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service #cluster of postgres pods
spec:
  type: ClusterIP
  selector:
    component: postgres  
  ports:
    - port: 5432 # Other port that needs comunicate with postgres-cluster-ip-service
      targetPort: 5432 # Port that needs postgres-cluster-ip-service Service to comunicate with postgres pods
      

